version: '2'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: wallet
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
#  db-gui:
#    image: mongo-express:latest
#    depends_on:
#      - db
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_SERVER: db
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
