version: '2'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: wallet
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
