server:
  port: 8083
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: wallet
      authentication-database: admin
  cloud:
    stream:
      bindings:
        user-events:
          destination: user-events
          group: transaction
          content-type: application/json
        output:
          destination: transaction-events
          content-type: application/json
logging:
  level:
    org.springframework.data.mongodb: info
