server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: wallet
      authentication-database: admin
  cloud:
    stream:
      bindings:
        input:
          destination: user-events
          group: user-view
          content-type: application/json
