server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: wallet
      authentication-database: admin
  cloud:
    stream:
      bindings:
        output:
          destination: user-events
          content-type: application/json
logging:
  level:
    org.springframework.data.mongodb: info
